### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by karl-ulyanov** [Holiverh/python-valve#22]
Python 2.7 on Windows. 
Attempting to use RCON and I get this error output:

C:\Users\Administrator\Desktop\steamcmd>python r.py
Traceback (most recent call last):
  File "r.py", line 6, in <module>
    with RCON(SERVER_ADDRESS, PASSWORD) as rcon:
  File "build\bdist.win32\egg\valve\source\rcon.py", line 126, in __enter__
  File "build\bdist.win32\egg\valve\source\rcon.py", line 250, in authenticate
  File "build\bdist.win32\egg\valve\source\rcon.py", line 226, in __enter__
  File "build\bdist.win32\egg\valve\source\rcon.py", line 199, in process
IndexError: list index out of range

My script is basically just your example with my server info filled in.

from valve.source.rcon import RCON

SERVER_ADDRESS = ("127.0.0.1", 32330)
PASSWORD = "SNIP"

with RCON(SERVER_ADDRESS, PASSWORD) as rcon:
    print(rcon("listplayers"))

**Comment by Holiverh** [comment]
This is perhaps not what you want to hear, but: I've started on a [new implementation of the RCON stuff ](https://github.com/Holiverh/python-valve/tree/rcon-rewrite) so that's it's unlikely I'll ever get around to fixing this  for `0.1.x` honestly. However, hopefully the new version, when it's finished, will fix this as well as having a generally nicer API and implementation.

Although saying that: this is honestly quite an odd bug you've got here. As I understand it the protocol is meant to guard against this ever happening. If you could provide an application ID and version number of the server you were experienced this with that'd be handy.

**Comment by karl-ulyanov** [comment]
I'm trying to use Python to interact with a game called Ark Survival Evolved which has really bad RCON implementation. It's actually so horribly badly coded it just stops responding to queries and randomly disconnects RCON clients for various reasons. And may or may not be related to server crashes on the linux codebase for the game. Anyway: 
Gameserver AppID is 376030.
Any version of the gameserver will have the same problem because they haven't bothered to fix their RCON/Async TCP Sockets for the game. 

I'll test out your rewrite later on to see what happens.

**Comment by Holiverh** [comment]
Thanks. I'll try to get around to testing it against an Ark server whilst writing the new stuff.

**Comment by Holiverh** [comment]
Just a heads up that the [new RCON interface](https://github.com/Holiverh/python-valve/blob/af56a05d4cd32977df13e0631df8482afa132f5c/valve/source/rcon.py) is in a somewhat usable state if you wanted to try it out. Although, of course, I wouldn't be too optimistic as it sounds like Ark's implementation is somewhat broken, to say the least.
